name: Build and Release
on: 
  push:
    paths:
      - 'src/**'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
            bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create env file
        run: |
            touch .env
            echo "DATABASE_HOST=${{secrets.DATABASE_HOST}}" > .env
            echo "DATABASE_USER=${{secrets.DATABASE_USER}}" >> .env
            echo "DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}" >> .env
            echo "DATABASE_NAME=${{secrets.DATABASE_NAME}}" >> .env
            echo "EMAIL_PASSWORD=${{secrets.EMAIL_PASSWORD}}" >> .env
            echo "EMAIL_SERVICE=${{secrets.EMAIL_SERVICE}}" >> .env
            echo "EMAIL_TEST=${{secrets.EMAIL_TEST}}" >> .env
            echo "EMAIL_USER=${{secrets.EMAIL_USER}}" >> .env
            echo "SQL_SSL_MODE=${{secrets.SQL_SSL_MODE}}" >> .env

      - name: ESLint
        run: bun eslint

      - name: Unit tests
        run: |
            bun ./src/utility/create_config.ts
            bun test database
            bun test email