name: Build and Release
on: 
  push:
    paths:
      - 'src/**'

  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
            bun-version: canary

      - name: ESLint
        run: bun eslint